edx/frontend-lib-learning-assistant

.releaserc

The release GitHub action on the previous pull request failed with the following error.
>
SemanticReleaseError: The release branches are invalid in the `branches` configuration.
at default (file:///home/runner/work/frontend-lib-learning-assistant/frontend-lib-learning-assistant/node_modules/semantic-release/lib/get-error.js:6:10)
at file:///home/runner/work/frontend-lib-learning-assistant/frontend-lib-learning-assistant/node_modules/semantic-release/lib/branches/index.js:45:19
at Array.reduce (<anonymous>)
at default (file:///home/runner/work/frontend-lib-learning-assistant/frontend-lib-learning-assistant/node_modules/semantic-release/lib/branches/index.js:35:[46](https://github.com/edx/frontend-lib-learning-assistant/actions/runs/5754323807/job/15599367963#step:7:47))
at …

fix: replace incorrect branch key with correct branches key in releaserc file

---

package-lock.json
package.json
src/components/ToggleXpertButton/index.jsx
src/data/slice.js
src/data/thunks.js
src/widgets/Xpert.jsx

This PR adds the following two segment events:
- an event sent for each message added, containing a conversation ID (created as part of state initialization), course ID, and the message itself
- an event sent each time the chat UI is opened, containing the course ID
As part of this PR, I've also passed in the course ID as a prop to the Xpert widget, which would have been a necessary add to create the response URL anyway.

feat: add segment events

---

README.rst
package-lock.json
package.json
src/components/ChatBox/index.jsx
src/components/Sidebar/index.jsx
src/data/slice.js
src/data/thunks.js
src/index.jsx
src/widgets/Xpert.jsx

This pull request represents a set of fixes and improvements necessary to install this library into the [Learning MFE](https://github.com/openedx/frontend-app-learning). Additional work on this library is necessary before it's possible to install it into the [Learning MFE](https://github.com/openedx/frontend-app-learning) (e.g. styling fixes, component structure improvements, changes to the [Learning MFE](https://github.com/openedx/frontend-app-learning), etc.), but this pull request contains an initial set of fixes for review.
This pull request includes the following changes:
* moving dependencies from `dependencies` to `devDependencies` and `peerDependencies` in `package.json`
* fixing the way the `learningAssistant` reducer is exported from `slice.js`
* fixing the way we call thunks by …

Various fixes and improvements to enable installation into Learning MFE

---

src/components/Sidebar/index.jsx

Send a hotjar event when a user closes the chat UI. This event is set up to trigger a feedback survey to evaluate usage of the tool.

feat: trigger hotjar event on chat close

---

src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.scss

This commit changes the CSS button element selector in the `ToggleXpertButton` to a CSS class selector (i.e. `toggle`). This is because the button selector was being applied in the `frontend-app-learning application` and causing changes to the page style.
Eventually, it may be nice to use something like CSS modules or styled components to scope our CSS to this component, but, for now, this will do.
**JIRA**: [MST-2034](https://2u-internal.atlassian.net/browse/MST-2034) (private)
**NOTE**: See the line above the video camera icon.
**Before**
**After**

Change CSS button element selector to class selector in ToggleXpertButton component.

---

package-lock.json
package.json
src/components/APIError/index.jsx
src/components/Sidebar/index.jsx
src/data/slice.js
src/data/thunks.js
src/utils/utils.test.jsx
src/widgets/Xpert.test.jsx

If the completion API endpoint returns with a non 200 response, we should show an error message to the user. The error message should clear:
- if the user submits a new message
- if a user hits the "clear" button

feat: add error message

---

src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.scss
src/widgets/Xpert.test.jsx

Update call to action button and add ability to dismiss message.
With call to action:
With call to action dismissed:

feat: update call to action message

---

src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.scss

Without the `position-fixed` class name, the toggle icon would move when clicked. This change prevents the icon from moving as it is clicked.

fix: prevent icon button from moving on click

---

src/components/ToggleXpertButton/index.jsx
src/widgets/Xpert.test.jsx

This pull request fixes a bug where the toggle button and action message remain in the DOM when the sidebar is open. Typically, they aren't visible because they're obfuscated by the open sidebar. However, on smaller screen sizes, or when the window is made smaller, the toggle button and action message are visible behind the sidebar. This commit conditionally renders the toggle button and action message only when the sidebar is closed.
JIRA: [MST-2092](https://2u-internal.atlassian.net/browse/MST-2092) (private)
**Before**
https://github.com/edx/frontend-lib-learning-assistant/assets/11871801/886d210f-a3cf-48b2-af85-847e8eea147d
**After**
https://github.com/edx/frontend-lib-learning-assistant/assets/11871801/938880f1-a28e-4680-9167-41e307f73fad

Conditionally render toggle button and action message only when the sidebar is closed.

---

src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.scss
src/data/slice.js
src/data/thunks.js
src/widgets/Xpert.jsx
src/widgets/Xpert.test.jsx

If content tools are enabled for a course, the chat toggle should appear above the content tools. If the chat sidebar is open, the content tools will not display over the chat sidebar either.
Old behavior:
New behavior:

fix: chat button should appear above content tools

---

src/components/ToggleXpertButton/index.jsx

In order to diagnose low usage rates, we're temporarily adding Segment events for rendering the toggle Xpert button and for closing the call-to-action message. This will help us determine whether the Xpert toggle button is being successfully rendered and whether the Xpert is being ignored by tracking whether learners close the call-to-action message at a high rate.
At a minimum, we expect to remove the Segment event for rendering the toggle Xpert button, because this will be a very noisy Segment event. We plan to leave it in for a few days just to accumulate data. We will evaluate whether to keep the call-to-action dismissal Segment event based on the data.
Note: This commit probably should be a `temp` commit, but that won't trigger a semantic release, so `feat` seems like the most …

Add additional Segment eventing for rendering toggle and closing call-to-action.

---

src/components/ToggleXpertButton/index.jsx

In #25, we added a Segment event for rendering the Xpert toggle button. This results in test failures in the downstream frontend-app-learning. These failures are likely due to the fact that the frontend-app-learning test is unable to mock out the frontend-platform module installed in this library. This results in failures, because the analytics service is not configured in the frontend-app-learning tests. In light of that, we've decided to move the render Segment event to the Chat component in the frontend-app-learning, which wraps the Xpert component.
**Jira:** None

fix: remove Segment event for rendering toggle

---

src/components/Sidebar/index.jsx
src/components/ToggleXpertButton/index.jsx
src/widgets/Xpert.test.jsx

If a user dismisses the CTA, that dismissal should be persisted. Additionally, we would only like to trigger the survey after a user has interacted with the learning assistant, so the hotjar event should only be triggered after a user sends and receives a message.

feat: persist cta dismissal and change survey trigger

---

src/components/Disclosure/index.jsx

feat: update alpha to beta

---

src/components/ToggleXpertButton/index.jsx
src/data/thunks.js

The product tour experiment has been rolled out to 100% of users. The rollout should now be implemented via code changes as well so that the experiment can be turned off.
This PR is largely a reversal of https://github.com/edx/frontend-lib-learning-assistant/pull/29, specifically any experiment related code, but keeps the product tour code in tact and functional.

feat: rollout product tour

---

package-lock.json
src/components/Disclosure/index.jsx
src/components/MessageForm/index.jsx
src/components/Sidebar/index.jsx
src/data/api.js
src/data/thunks.js
src/widgets/Xpert.jsx

**Jira**: [COSMO-75](https://2u-internal.atlassian.net/browse/COSMO-75)
This commit modifies the `Xpert` components to accept a new `unitId` prop, which presents the unit usage key in which the `Xpert` is being rendered. This unit ID is forwarded to the chat completion backend API.

feat: receive unitId as prop and forward to learning-assistant backend

---

src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.scss

Because the popup modal did not share the same parent div as our toggle component, the position of the modal popup and the toggle would differ as the courseware page loaded. 
As part of this PR I also fixed some margins for both the toggle and the popup to ensure that they do not overlay over the course tools (i.e. calculator and notes). 
Before:
After:

fix: modal popup should be grouped with toggle button

---

src/data/api.js
src/data/slice.js
src/data/thunks.js
src/widgets/Xpert.jsx
src/widgets/Xpert.test.jsx

**Jira**: [COSMO-161](https://2u-internal.atlassian.net/browse/COSMO-161)
**Prerequisite**: https://github.com/edx/learning-assistant/pull/63 must be merged and deployed before this pull request is merged and deployed.
This commit uses a new GET endpoint published on the Learning Assistant backend to determine whether the Learning Assistant feature is enabled. If the features is not enabled, the Learning Assistant is not rendered, and vice-versa.
This is an alternative to using the `edx-platform` Courseware API to determine whether the feature is enabled. The reason this decision was made was so as not to introduce 2U-specific code into the platform in the form of calls to the `learning-assistant` plugin and it's models and APIs. This allows the Learning Assistant frontend to encapsulate …

feat: use backend GET endpoint to determine whether to show Learning Assistant

---

src/components/ChatBox/ChatBox.scss

I noticed that the scrollbar on stage and prod was now green, which was not the case previously. I discovered that we had some custom css styling on the scrollbar, that was now appearing. 
Before:
After:

feat: remove scrollbar css styling

---

src/components/Sidebar/Sidebar.scss
src/components/ToggleXpertButton/index.scss

Because the new sidebar components have been released to prod, and in rendering have a higher z-index, we need to manually set the z-index for Xpert to ensure that it overlays on top of other components visible in the courseware. 
Before:
After:

feat: xpert should have z-index priority

---

src/components/ToggleXpertButton/index.scss

The Xpert toggle button was appearing with a larger width than intended in safari. No width was specified (either by percentage or pixel), so browsers likely calculated/inferred the width for the toggle element differently. 
This change specifies a pixel width, so that the button appears the same across browsers.
Before:
After:

fix: update toggle button width

---

package-lock.json
package.json

What changed?
- Update `@edx/frontend-platform` package and update peer dependency. 
Currently, this block the effort to upgrade  `@edx/frontend-platform` on `frontend-app-learning`

fix: upgrade frontend-platform and update peer dependency

---

src/components/ToggleXpertButton/index.scss

This was getting overridden by the paragon .btn border style
I wasn't able to reproduce the issue locally but I think the level of specificity wasn't high enough originally.

fix: rounded border on widget

---

.github/workflows/ci.yml

- `set-output` has been deprecated by GitHub and it is suggested to be replaced by GitHub.

fix: replace set-output github actions

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json
src/components/Disclosure/index.jsx
src/components/Sidebar/index.jsx
src/components/Sidebar/index.test.jsx
src/components/ToggleXpertButton/index.jsx
src/components/ToggleXpertButton/index.test.jsx
src/constants/experiments.js
src/data/api.js
src/data/slice.js
src/data/thunks.js
src/hooks/useOptimizelyExperiment.js
src/hooks/useOptimizelyExperiment.test.js
src/setupTest.js
src/utils/surveyMonkey.js
src/utils/utils.test.jsx
src/widgets/Xpert.jsx
src/widgets/Xpert.test.jsx

This integrates Optimizely's hooks for the new XPert prompt experiment.

feat: Integrated Optimizely Prompt Experiment

---

src/data/thunks.js
src/utils/optimizelyExperiment.js

Optimizely always expects the userId to be passed as a string. Because the user ID is currently being passed as an integer, calls to the `track` function are failing on stage right now.

fix: modify optimizely tracking calls

---

src/experiments/experimentHooks.js

[COSMO-400 🔒](https://2u-internal.atlassian.net/browse/COSMO-400)
Based on our observation, it seems that using `autoUpdate` option in Optimizely's `useDecision()` hook causes Optimizely to be updated in every component update. This was removed as it was not strictly required.

fix: Removed autoupdate due to constant updates

---

src/data/optimizely.js
src/experiments/ExperimentsProvider.jsx
src/utils/optimizelyExperiment.js

There was a problem with Optimizely's initialization.
Refactored  `getOptimizely()` to work as a singleton and added some guard rails in case we have to wait for initialization.

fix: Optimizely init fix

---

package-lock.json
package.json

This update is related with issue https://github.com/openedx/frontend-app-learning/issues/1482: Reducing specificity in redux peer dependency allows more flexibility on `fontend-app-learning` to update it.

Reduced specificity on Redux rependency

---

package-lock.json
package.json
src/data/api.js
src/data/api.test.js
src/data/thunks.js
src/data/thunks.test.js
src/hooks/index.js
src/hooks/message-history.js
src/hooks/message-history.test.js
src/widgets/Xpert.jsx
src/widgets/Xpert.test.jsx

Added implementation for fetching the chat history when rendering Xpert Learning Assistant.
- Added `test:watch script`, very useful to use when working on unit tests.
- Updated `caniuse-lite` database.
https://github.com/user-attachments/assets/885bc59b-880b-4f5a-8c55-846b1d0c81b7

feat: Fetches chat history when loading Xpert

---

package-lock.json
package.json

There was a typo on an update for the `redux` npm package dependency. I've used `4^` instead of `^4`.

fix: Fixed redux npm package version reference

---

src/components/Sidebar/index.jsx
src/components/Sidebar/index.test.jsx
src/data/slice.js
src/data/thunks.js
src/widgets/Xpert.test.jsx

As part of the message history roll out, the clear button should no longer be included in the chat UI. 
UI with clear button removed:

feat: remove clear button from chat UI

---

src/components/ChatBox/index.jsx
src/components/ChatBox/index.test.jsx
src/components/MessageDivider/MessageDivider.scss
src/components/MessageDivider/index.jsx

[COSMO-544](https://2u-internal.atlassian.net/browse/COSMO-544)
This PR adds the Today message divider which divides old and new messages. See screenshot below:

feat: add today message divider

---

src/components/Sidebar/Sidebar.scss
src/components/Sidebar/index.jsx
src/widgets/Xpert.test.jsx

This pull request includes changes to the `Sidebar` component to update its styling and improve its functionality. The most important changes include adding a new header with a logo, modifying the separator styling, and updating the corresponding tests.
Old sidebar header:
New sidebar h
eader:

feat: update header for sidebar

---

src/widgets/Xpert.jsx

As we introduce the audit trial experience, the Xpert component must be aware of whether or not a learner is eligible for upgrade. This PR introduces a new prop which can then be used in child components to determine whether or not to display trial language/UX.

feat: introduce new prop for upgrade eligibility

---

src/data/thunks.js
src/data/thunks.test.js

[COSMO-547](https://2u-internal.atlassian.net/browse/COSMO-547)
Modify segment event to remove message contents and PII.

feat: modify segment event to remove message content

---

src/components/Disclosure/__snapshots__/index.test.jsx.snap
src/components/Disclosure/index.jsx
src/components/Disclosure/index.test.jsx
src/components/Sidebar/index.jsx
src/components/Sidebar/index.test.jsx
src/components/UpgradeButton/UpgradeButton.scss
src/components/UpgradeButton/index.jsx
src/components/UpgradeButton/index.test.jsx
src/components/UpgradePanel/UpgradePanel.scss
src/components/UpgradePanel/UpsellBullets/UpsellBullets.jsx
src/components/UpgradePanel/UpsellBullets/index.jsx
src/components/UpgradePanel/__snapshots__/index.test.jsx.snap
src/components/UpgradePanel/index.jsx
src/components/UpgradePanel/index.test.jsx
src/hooks/use-course-upgrade.js
src/hooks/use-course-upgrade.test.jsx
src/widgets/Xpert.jsx

When a learner is eligible for upgrade, and their audit trial is expired, an upgrade panel should be shown with a button that takes a learner to the purchase page. Different value props will be shown on the upgrade panel depending on whether or not the course has FBE enabled. The definition for whether or not FBE is enabled has been duplicated from `frontend-plugin-advertisements` (see https://github.com/edx/frontend-plugin-advertisements/blob/7eac0c8caf701c17a2aba1f1dbb5c942aea8c290/src/upgrade-modal/DefaultUpgradeModal.jsx#L71). 
Upgrade panel with FBE:
Upgrade without FBE:

feat: display upgrade panel when audit trial is expired

---

src/components/ChatBox/ChatBox.scss
src/components/ChatBox/index.jsx
src/components/ChatBox/index.test.jsx
src/components/Message/index.jsx
src/components/MessageForm/MessageForm.scss
src/components/MessageForm/index.jsx
src/components/Sidebar/Sidebar.scss
src/components/Sidebar/index.jsx
src/utils/scroll.js
src/utils/scroll.test.js
src/widgets/Xpert.test.jsx

Ticket: [COSMO-597](https://2u-internal.atlassian.net/browse/COSMO-597)🔒
This PR changes the way the chat scroll behaves. Its default behavior to have a smooth scroll down whenever a new message appears causes a weird experience on opening with an existing chat history to smooth scroll all messages down each time it opens. These changes makes the first render to scroll instantly to the last message on open and then uses smooth scrolling on each new message.
Additionally, it tweaks the UI to make it closer to the original design and added some extra tweaks.
#Screenshots
> [!NOTE]  
> Notice some UI improvements like using shadows at the top and bottom of the chat scroll list, the shadows now are cast over the messages rather than clipping behind them and updated some sizes and paddings to …

feat: Update to scroll behavior and UX tweaks

---

src/components/MessageForm/MessageForm.scss
src/utils/_variables.scss

We are using some [Paragon variable references in our SCSS](https://github.com/edx/brand-edx.org/blob/master/paragon/_variables.scss) but these might not be available during the CI checks.
We need to add the vars locally as defaults to workaround this.

fix: Fixed Paragon scss var reference for CI

---

package-lock.json
package.json

Part of https://github.com/openedx/axim-engineering/issues/23
This updates the `@edx/brand` alias to point to the `brand-openedx` package at
the `openedx` scope. This does not impact imports because this package is used
via an alias.

chore: Update to the new version of brand-openedx in the new scope

---

src/widgets/Xpert.jsx
src/widgets/Xpert.test.jsx

If a user is eligible for upgrade and part of the `control` variation, the Xpert UI should not be visible to them.

feat: hide xpert if user is in control variation

---

src/hooks/use-course-upgrade.js
src/hooks/use-course-upgrade.test.jsx

**Jira**: [COSMO-675](https://2u-internal.atlassian.net/browse/COSMO-675) (private)
This commit updates the logic that is used to determine whether an audit trial is expired. Originally, an audit trial was considered expired if the days remaining was less than 0. This change considers an audit trial expired if the days remaining is less than or equal to 0.
This is consistent with the logic used to determine whether an audit trial is expired on the backend [here](https://github.com/edx/learning-assistant/blob/93d620e49447c54d6e70f7816c6823dcc5eb2534/learning_assistant/api.py#L337).
The bug this commit fixes was that learners that accessed Xpert with an audit trial that expired that day would still be shown Xpert because the days remaining was 0 or -0, and, thus, was not considered expired. …

fix: update expiration logic to consider trials with 0 or -0 days remaining expired

---

src/components/Disclosure/__snapshots__/index.test.jsx.snap
src/components/Disclosure/index.jsx
src/components/UpgradeButton/index.jsx
src/components/UpgradePanel/__snapshots__/index.test.jsx.snap

https://2u-internal.atlassian.net/browse/COSMO-677
The following links now open in a new tab rather than on the same tab:
- upgrade link on the intro screen
- privacy policy link on the intro screen
- upgrade link on the final upgrade screen

feat: open all hyperlinks in new tab

---

src/components/Sidebar/Sidebar.scss
src/components/Sidebar/index.jsx
src/components/Sidebar/index.test.jsx
src/data/thunks.js

This commit fixes a bug where the days remaining banner appears after an audit trial learner sends their first message. In this case, the days remaining is not displayed until the call to the chat summary endpoint completes. This commit adds a loading spinner to the banner that appears while that call is in progress.
**Jira**: [COSMO-678](https://2u-internal.atlassian.net/browse/COSMO-678)
**Demo**
https://github.com/user-attachments/assets/395aa079-7e72-4cbd-a929-6f48e49b1ee3

fix: days remaining banner appears before days remaining is computed

---

package-lock.json
package.json
src/index.scss

This PR updates frontend-lib-learning-assistant with the compatibility for CSS Variables and Design Tokens, the new styling paradigm for the frontend. 
**Changes:**
1. Update peerDependencies to allow  `paragon`   version 23.x
2. Delete index.scss 
**Important**
There is a breaking change due to the paragon imports in the index.scss (if it is possible we want to check the relevance of the file otherwise modify it to release a major instead of a major)

feat: support paragon to 23

---

src/data/thunks.js
src/data/thunks.test.js
src/widgets/Xpert.test.jsx

This pull request introduces support for a feature flag (`FEATURE_ENABLE_CHAT_V2_ENDPOINT`) to toggle between old and new chat endpoints, along with corresponding updates to unit tests. Additionally, it modifies test cases for the `Xpert` widget to include a new `isUpgradeEligible` prop, ensuring consistency across tests.
* [`src/data/thunks.js`](diffhunk://#diff-f708120055e193e6e1c566fefb57a208b514e2fd0f8944fc91ee1f0c97b0cd34R78-R86): Added logic to check the `FEATURE_ENABLE_CHAT_V2_ENDPOINT` flag and dispatch messages differently based on the flag's value. This enables toggling between the old and new chat endpoints.
* [`src/data/thunks.test.js`](diffhunk://#diff-64688506fa5a6fcbe2cd60fea5be1774aae123fd6fb19fcda6906aa8ce2c7635R78-R86): Added test cases to validate behavior when the …

feat: Implement feature toggle for chat response endpoint
